pipeline {
    agent { label 'maven' }
    stages {
        stage("Build") {
            steps {
              sh 'cd student'
              sh 'mvn clean package -DskipTests'
            }
        }
        stage("docker build") {
            steps {
                echo "docker build"
            }
        }
        stage("deploy") {
                    steps {
                        echo "deploy to k8s"
                    }
                }
    }
}
